# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/lojn/PycharmProjects/ljz-tools/ui/PageTableWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets

import qfluentwidgets

class Ui_PageTableWidget(object):
    def setupUi(self, PageTableWidget):
        PageTableWidget.setObjectName("PageTableWidget")
        PageTableWidget.resize(1206, 786)
        self.verticalLayout = QtWidgets.QVBoxLayout(PageTableWidget)
        self.verticalLayout.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tbw_table = QtWidgets.QTableWidget(PageTableWidget)
        self.tbw_table.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tbw_table.setStyleSheet("\n"
"/* 如下代码设置列表左上角那个格子的边框线 */\n"
"QTableCornerButton::section{ \n"
"  border-top:0px solid #E5E5E5;\n"
"  border-left:0px solid #E5E5E5;\n"
"  border-right:0.5px solid #E5E5E5;\n"
"  border-bottom: 0.5px solid #E5E5E5;\n"
"  background-color:white;\n"
"}\n"
"/* 如下代码设置横向表格头的间隔线，有四个方向的间隔线,不需要间隔线的可以设置为0px */\n"
"QHeaderView::section{\n"
"  border-top:0px solid #E5E5E5;\n"
"  border-left:0px solid #E5E5E5;\n"
"  border-right:0.5px solid #E5E5E5;\n"
"  border-bottom: 0.5px solid #E5E5E5;\n"
"  background-color:white;\n"
"  padding:4px;\n"
"}\n"
"/* 如下代码设置纵向表格头的间隔线，有四个方向的间隔线, 不需要间隔线的可以设置为0px */\n"
"QHeaderView::section{\n"
"  border-top:0px solid #E5E5E5;\n"
"  border-left:0px solid #E5E5E5;\n"
"  border-right:0.5px solid #E5E5E5;\n"
"  border-bottom: 0.5px solid #E5E5E5;\n"
"  background-color:white;\n"
"  padding:4px;\n"
"}\n"
"/* 选中项目 */\n"
"QTableWidget::item:selected {\n"
"  background-color: rgb(225, 227, 230);  /*rgb(0, 159, 170) (225, 227, 230)*/\n"
"  border-radius: 3px; /*圆角度*/\n"
"}")
        self.tbw_table.setRowCount(10)
        self.tbw_table.setColumnCount(6)
        self.tbw_table.setObjectName("tbw_table")
        self.verticalLayout.addWidget(self.tbw_table)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cbb_cnt = qfluentwidgets.ComboBox(PageTableWidget)
        self.cbb_cnt.setObjectName("cbb_cnt")
        self.cbb_cnt.addItem("")
        self.cbb_cnt.addItem("")
        self.cbb_cnt.addItem("")
        self.cbb_cnt.addItem("")
        self.horizontalLayout.addWidget(self.cbb_cnt)
        self.btn_first = qfluentwidgets.PushButton(PageTableWidget)
        self.btn_first.setMinimumSize(QtCore.QSize(100, 0))
        self.btn_first.setObjectName("btn_first")
        self.horizontalLayout.addWidget(self.btn_first)
        self.btn_pre = qfluentwidgets.PushButton(PageTableWidget)
        self.btn_pre.setMinimumSize(QtCore.QSize(100, 0))
        self.btn_pre.setObjectName("btn_pre")
        self.horizontalLayout.addWidget(self.btn_pre)
        self.edt_cur_page = LineEdit(PageTableWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edt_cur_page.sizePolicy().hasHeightForWidth())
        self.edt_cur_page.setSizePolicy(sizePolicy)
        self.edt_cur_page.setMaximumSize(QtCore.QSize(70, 16777215))
        self.edt_cur_page.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edt_cur_page.setObjectName("edt_cur_page")
        self.horizontalLayout.addWidget(self.edt_cur_page)
        self.label = StrongBodyLabel(PageTableWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lab_cnt_page = BodyLabel(PageTableWidget)
        self.lab_cnt_page.setObjectName("lab_cnt_page")
        self.horizontalLayout.addWidget(self.lab_cnt_page)
        self.btn_next = qfluentwidgets.PushButton(PageTableWidget)
        self.btn_next.setMinimumSize(QtCore.QSize(100, 0))
        self.btn_next.setObjectName("btn_next")
        self.horizontalLayout.addWidget(self.btn_next)
        self.btn_last = qfluentwidgets.PushButton(PageTableWidget)
        self.btn_last.setMinimumSize(QtCore.QSize(100, 0))
        self.btn_last.setObjectName("btn_last")
        self.horizontalLayout.addWidget(self.btn_last)
        self.btn_jump = qfluentwidgets.PushButton(PageTableWidget)
        self.btn_jump.setMinimumSize(QtCore.QSize(100, 0))
        self.btn_jump.setObjectName("btn_jump")
        self.horizontalLayout.addWidget(self.btn_jump)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_export = qfluentwidgets.PushButton(PageTableWidget)
        self.btn_export.setMinimumSize(QtCore.QSize(100, 0))
        self.btn_export.setObjectName("btn_export")
        self.horizontalLayout.addWidget(self.btn_export)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(PageTableWidget)
        QtCore.QMetaObject.connectSlotsByName(PageTableWidget)

    def retranslateUi(self, PageTableWidget):
        _translate = QtCore.QCoreApplication.translate
        PageTableWidget.setWindowTitle(_translate("PageTableWidget", "PageTableWidget"))
        self.cbb_cnt.setItemText(0, _translate("PageTableWidget", "100条/页"))
        self.cbb_cnt.setItemText(1, _translate("PageTableWidget", "1000条/页"))
        self.cbb_cnt.setItemText(2, _translate("PageTableWidget", "10000条/页"))
        self.cbb_cnt.setItemText(3, _translate("PageTableWidget", "100000条/页"))
        self.btn_first.setText(_translate("PageTableWidget", "首页"))
        self.btn_pre.setText(_translate("PageTableWidget", "上一页"))
        self.edt_cur_page.setText(_translate("PageTableWidget", "0"))
        self.label.setText(_translate("PageTableWidget", "/"))
        self.lab_cnt_page.setText(_translate("PageTableWidget", "0"))
        self.btn_next.setText(_translate("PageTableWidget", "下一页"))
        self.btn_last.setText(_translate("PageTableWidget", "尾页"))
        self.btn_jump.setText(_translate("PageTableWidget", "跳转"))
        self.btn_export.setText(_translate("PageTableWidget", "导出"))
from qfluentwidgets import BodyLabel, LineEdit, StrongBodyLabel
