# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/lojn/PycharmProjects/ljz-tools/表结构转换/TableTransUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets

import qfluentwidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1428, 777)
        MainWindow.setStyleSheet("QMainWindow {\n"
"     background-color: rgb(237, 246, 248); /* rgb(240, 244, 249)(237, 246, 248) */\n"
" }")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Pivot = qfluentwidgets.Pivot(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Pivot.sizePolicy().hasHeightForWidth())
        self.Pivot.setSizePolicy(sizePolicy)
        self.Pivot.setObjectName("Pivot")
        self.Pivot.addItem("Item1", "")
        self.Pivot.addItem("Item2", "")
        self.horizontalLayout.addWidget(self.Pivot)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setStyleSheet("#Item1,#Item2,#tab_sql,#tab_db,#tab_settings {\n"
"  background-color: rgb(247, 249, 252); /* rgb(237, 246, 248) */\n"
"  border: 1px solid rgb(220, 220, 220); /* 边框宽度、样式和颜色 */\n"
"  border-radius: 8px; /*圆角度*/\n"
" }")
        self.stackedWidget.setObjectName("stackedWidget")
        self.Item1 = QtWidgets.QWidget()
        self.Item1.setObjectName("Item1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Item1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cbb_setting = qfluentwidgets.ComboBox(self.Item1)
        self.cbb_setting.setMinimumSize(QtCore.QSize(200, 0))
        self.cbb_setting.setObjectName("cbb_setting")
        self.cbb_setting.addItem("")
        self.cbb_setting.addItem("")
        self.cbb_setting.addItem("")
        self.horizontalLayout_2.addWidget(self.cbb_setting)
        self.btn_trans = qfluentwidgets.PushButton(self.Item1)
        self.btn_trans.setObjectName("btn_trans")
        self.horizontalLayout_2.addWidget(self.btn_trans)
        self.btn_ddl = qfluentwidgets.PushButton(self.Item1)
        self.btn_ddl.setObjectName("btn_ddl")
        self.horizontalLayout_2.addWidget(self.btn_ddl)
        self.btn_clear_table = qfluentwidgets.PushButton(self.Item1)
        self.btn_clear_table.setObjectName("btn_clear_table")
        self.horizontalLayout_2.addWidget(self.btn_clear_table)
        self.btn_export = qfluentwidgets.PushButton(self.Item1)
        self.btn_export.setObjectName("btn_export")
        self.horizontalLayout_2.addWidget(self.btn_export)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.btn_ex = qfluentwidgets.PushButton(self.Item1)
        self.btn_ex.setObjectName("btn_ex")
        self.horizontalLayout_2.addWidget(self.btn_ex)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tbw_table = ActionTableWidget(self.Item1)
        self.tbw_table.setRowCount(100)
        self.tbw_table.setColumnCount(12)
        self.tbw_table.setObjectName("tbw_table")
        item = QtWidgets.QTableWidgetItem()
        self.tbw_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_table.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_table.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_table.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_table.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_table.setHorizontalHeaderItem(11, item)
        self.horizontalLayout_3.addWidget(self.tbw_table)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.stackedWidget.addWidget(self.Item1)
        self.Item2 = QtWidgets.QWidget()
        self.Item2.setStyleSheet("#widget_setting_left,#widget_setting_right {\n"
"  background-color: rgb(241, 243, 246); /* rgb(237, 246, 248) */\n"
"  border: 1px solid rgb(220, 220, 220); /* 边框宽度、样式和颜色 */\n"
"  border-radius: 8px; /*圆角度*/\n"
" }")
        self.Item2.setObjectName("Item2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.Item2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.widget_setting_left = QtWidgets.QWidget(self.Item2)
        self.widget_setting_left.setStyleSheet("")
        self.widget_setting_left.setObjectName("widget_setting_left")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_setting_left)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_add_setting = qfluentwidgets.PushButton(self.widget_setting_left)
        self.btn_add_setting.setObjectName("btn_add_setting")
        self.horizontalLayout_4.addWidget(self.btn_add_setting)
        self.btn_del_setting = qfluentwidgets.PushButton(self.widget_setting_left)
        self.btn_del_setting.setObjectName("btn_del_setting")
        self.horizontalLayout_4.addWidget(self.btn_del_setting)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.lsw_setting = ListWidget(self.widget_setting_left)
        self.lsw_setting.setStyleSheet("ListView,\n"
"ListWidget {\n"
"    background: transparent;\n"
"    background-color: rgb(255, 255, 255);\n"
"    outline: none;\n"
"    border: none;\n"
"    /* font: 13px \'Segoe UI\', \'Microsoft YaHei\'; */\n"
"    selection-background-color: transparent;\n"
"    alternate-background-color: transparent;\n"
"    padding-left: 4px;\n"
"    padding-right: 4px;\n"
"}\n"
"\n"
"ListView::item,\n"
"ListWidget::item {\n"
"    background: transparent;\n"
"    border: 1px;\n"
"    padding-left: 11px;\n"
"    padding-right: 11px;\n"
"    height: 35px;\n"
"}\n"
"\n"
"\n"
"ListView::indicator,\n"
"ListWidget::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 5px;\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    margin-right: 4px;\n"
"}\n"
"\n"
"")
        self.lsw_setting.setObjectName("lsw_setting")
        item = QtWidgets.QListWidgetItem()
        self.lsw_setting.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lsw_setting.addItem(item)
        self.verticalLayout_3.addWidget(self.lsw_setting)
        self.horizontalLayout_6.addWidget(self.widget_setting_left)
        self.widget_setting_right = QtWidgets.QWidget(self.Item2)
        self.widget_setting_right.setObjectName("widget_setting_right")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_setting_right)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btn_save_setting = qfluentwidgets.PushButton(self.widget_setting_right)
        self.btn_save_setting.setObjectName("btn_save_setting")
        self.horizontalLayout_5.addWidget(self.btn_save_setting)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.tbw_setting = ActionTableWidget(self.widget_setting_right)
        self.tbw_setting.setStyleSheet("")
        self.tbw_setting.setRowCount(50)
        self.tbw_setting.setObjectName("tbw_setting")
        self.tbw_setting.setColumnCount(8)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_setting.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_setting.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_setting.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_setting.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_setting.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_setting.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_setting.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_setting.setHorizontalHeaderItem(7, item)
        self.verticalLayout_4.addWidget(self.tbw_setting)
        self.horizontalLayout_6.addWidget(self.widget_setting_right)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 4)
        self.stackedWidget.addWidget(self.Item2)
        self.verticalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1428, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "表结构转换										Developed by LJZ，QQ：786824023"))
        self.Pivot.setItemText("Item1", _translate("MainWindow", "开始转换"))
        self.Pivot.setItemText("Item2", _translate("MainWindow", "转换配置"))
        self.cbb_setting.setItemText(0, _translate("MainWindow", "--选择配置文件--"))
        self.cbb_setting.setItemText(1, _translate("MainWindow", "配置1"))
        self.cbb_setting.setItemText(2, _translate("MainWindow", "配置2"))
        self.btn_trans.setText(_translate("MainWindow", "开始转换"))
        self.btn_ddl.setText(_translate("MainWindow", "生成DDL"))
        self.btn_clear_table.setText(_translate("MainWindow", "清空页面"))
        self.btn_export.setText(_translate("MainWindow", "导出Excel"))
        self.btn_ex.setText(_translate("MainWindow", "数据案例"))
        item = self.tbw_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "表英文名"))
        item = self.tbw_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "表中文名"))
        item = self.tbw_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "字段英文名"))
        item = self.tbw_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "字段中文名"))
        item = self.tbw_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "字段类型"))
        item = self.tbw_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "字段类型(自动)"))
        item = self.tbw_table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "长度(自动)"))
        item = self.tbw_table.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "精度(自动)"))
        item = self.tbw_table.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "转换后类型"))
        item = self.tbw_table.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "转换后长度"))
        item = self.tbw_table.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "转换后精度"))
        item = self.tbw_table.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "结果"))
        self.btn_add_setting.setText(_translate("MainWindow", "新增"))
        self.btn_del_setting.setText(_translate("MainWindow", "删除"))
        __sortingEnabled = self.lsw_setting.isSortingEnabled()
        self.lsw_setting.setSortingEnabled(False)
        item = self.lsw_setting.item(0)
        item.setText(_translate("MainWindow", "配置1"))
        item = self.lsw_setting.item(1)
        item.setText(_translate("MainWindow", "配置2"))
        self.lsw_setting.setSortingEnabled(__sortingEnabled)
        self.btn_save_setting.setText(_translate("MainWindow", "保存"))
        item = self.tbw_setting.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "源类型"))
        item = self.tbw_setting.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "目标类型"))
        item = self.tbw_setting.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "长度转换规则"))
        item = self.tbw_setting.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "长度转换值"))
        item = self.tbw_setting.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "精度转换规则"))
        item = self.tbw_setting.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "精度转换值"))
        item = self.tbw_setting.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "长度缺省值"))
        item = self.tbw_setting.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "精度缺省值"))
from qfluentwidgets import ListWidget
from 表结构转换.ActionTableWidget import ActionTableWidget
