# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/lojn/PycharmProjects/ljz-tools/表结构转换/TableTransUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets

import qfluentwidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1038, 594)
        MainWindow.setStyleSheet("QMainWindow {\n"
"     background-color: rgb(237, 246, 248); /* rgb(240, 244, 249)(237, 246, 248) */\n"
" }")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Pivot = qfluentwidgets.Pivot(self.centralwidget)
        self.Pivot.setObjectName("Pivot")
        self.Pivot.addItem("Item1", "")
        self.Pivot.addItem("Item2", "")
        self.horizontalLayout.addWidget(self.Pivot)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setStyleSheet("#Item1,#Item2,#tab_sql,#tab_db,#tab_settings {\n"
"  background-color: rgb(247, 249, 252); /* rgb(237, 246, 248) */\n"
"  border: 1px solid rgb(220, 220, 220); /* 边框宽度、样式和颜色 */\n"
"  border-radius: 8px; /*圆角度*/\n"
" }")
        self.stackedWidget.setObjectName("stackedWidget")
        self.Item1 = QtWidgets.QWidget()
        self.Item1.setObjectName("Item1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Item1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cbb_setting = qfluentwidgets.ComboBox(self.Item1)
        self.cbb_setting.setObjectName("cbb_setting")
        self.cbb_setting.addItem("")
        self.cbb_setting.addItem("")
        self.cbb_setting.addItem("")
        self.horizontalLayout_2.addWidget(self.cbb_setting)
        self.PushButton_2 = qfluentwidgets.PushButton(self.Item1)
        self.PushButton_2.setObjectName("PushButton_2")
        self.horizontalLayout_2.addWidget(self.PushButton_2)
        self.PushButton_3 = qfluentwidgets.PushButton(self.Item1)
        self.PushButton_3.setObjectName("PushButton_3")
        self.horizontalLayout_2.addWidget(self.PushButton_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.PushButton = qfluentwidgets.PushButton(self.Item1)
        self.PushButton.setObjectName("PushButton")
        self.horizontalLayout_2.addWidget(self.PushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tbw_table = PageTableWidget(self.Item1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbw_table.sizePolicy().hasHeightForWidth())
        self.tbw_table.setSizePolicy(sizePolicy)
        self.tbw_table.setObjectName("tbw_table")
        self.horizontalLayout_3.addWidget(self.tbw_table)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.stackedWidget.addWidget(self.Item1)
        self.Item2 = QtWidgets.QWidget()
        self.Item2.setStyleSheet("#widget_setting_left,#widget_setting_right {\n"
"  background-color: rgb(241, 243, 246); /* rgb(237, 246, 248) */\n"
"  border: 1px solid rgb(220, 220, 220); /* 边框宽度、样式和颜色 */\n"
"  border-radius: 8px; /*圆角度*/\n"
" }")
        self.Item2.setObjectName("Item2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.Item2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.widget_setting_left = QtWidgets.QWidget(self.Item2)
        self.widget_setting_left.setStyleSheet("")
        self.widget_setting_left.setObjectName("widget_setting_left")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_setting_left)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_add_setting = qfluentwidgets.PushButton(self.widget_setting_left)
        self.btn_add_setting.setObjectName("btn_add_setting")
        self.horizontalLayout_4.addWidget(self.btn_add_setting)
        self.btn_del_setting = qfluentwidgets.PushButton(self.widget_setting_left)
        self.btn_del_setting.setObjectName("btn_del_setting")
        self.horizontalLayout_4.addWidget(self.btn_del_setting)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.lsw_setting = ListWidget(self.widget_setting_left)
        self.lsw_setting.setStyleSheet("ListView,\n"
"ListWidget {\n"
"    background: transparent;\n"
"    background-color: rgb(255, 255, 255);\n"
"    outline: none;\n"
"    border: none;\n"
"    /* font: 13px \'Segoe UI\', \'Microsoft YaHei\'; */\n"
"    selection-background-color: transparent;\n"
"    alternate-background-color: transparent;\n"
"    padding-left: 4px;\n"
"    padding-right: 4px;\n"
"}\n"
"\n"
"ListView::item,\n"
"ListWidget::item {\n"
"    background: transparent;\n"
"    border: 1px;\n"
"    padding-left: 11px;\n"
"    padding-right: 11px;\n"
"    height: 35px;\n"
"}\n"
"\n"
"\n"
"ListView::indicator,\n"
"ListWidget::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 5px;\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    margin-right: 4px;\n"
"}\n"
"\n"
"")
        self.lsw_setting.setObjectName("lsw_setting")
        item = QtWidgets.QListWidgetItem()
        self.lsw_setting.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lsw_setting.addItem(item)
        self.verticalLayout_3.addWidget(self.lsw_setting)
        self.horizontalLayout_6.addWidget(self.widget_setting_left)
        self.widget_setting_right = QtWidgets.QWidget(self.Item2)
        self.widget_setting_right.setObjectName("widget_setting_right")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_setting_right)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btn_save_setting = qfluentwidgets.PushButton(self.widget_setting_right)
        self.btn_save_setting.setObjectName("btn_save_setting")
        self.horizontalLayout_5.addWidget(self.btn_save_setting)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.tbw_setting = TableWidget(self.widget_setting_right)
        self.tbw_setting.setStyleSheet("QTableView {\n"
"    background: transparent;\n"
"    outline: none;\n"
"    border: none;\n"
"    /* font: 13px \'Segoe UI\', \'Microsoft YaHei\'; */\n"
"    selection-background-color: transparent;\n"
"    alternate-background-color: transparent;\n"
"}\n"
"\n"
"QTableView[isBorderVisible=true] {\n"
"    border: 1px solid rgba(0, 0, 0, 15);\n"
"}\n"
"\n"
"QTableView::item {\n"
"    background: transparent;\n"
"    border: 0px;\n"
"    padding-left: 16px;\n"
"    padding-right: 16px;\n"
"    height: 35px;\n"
"}\n"
"\n"
"\n"
"QTableView::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 5px;\n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"\n"
"QHeaderView {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: transparent;\n"
"    color: rgb(96, 96, 96);\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    border: 1px solid rgba(0, 0, 0, 15);\n"
"    font: 13px \'Segoe UI\', \'Microsoft YaHei\', \'PingFang SC\';\n"
"}\n"
"\n"
"QHeaderView::section:horizontal {\n"
"    border-left: none;\n"
"    height: 33px;\n"
"}\n"
"\n"
"QTableView[isBorderVisible=true] QHeaderView::section:horizontal {\n"
"    border-top: none;\n"
"}\n"
"\n"
"QHeaderView::section:horizontal:last {\n"
"    border-right: none;\n"
"}\n"
"\n"
"QHeaderView::section:vertical {\n"
"    border-top: none;\n"
"}\n"
"\n"
"QHeaderView::section:checked {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QHeaderView::down-arrow {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: center right;\n"
"    margin-right: 6px;\n"
"    image: url(:/qfluentwidgets/images/table_view/Down_black.svg);\n"
"}\n"
"\n"
"QHeaderView::up-arrow {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: center right;\n"
"    margin-right: 6px;\n"
"    image: url(:/qfluentwidgets/images/table_view/Up_black.svg);\n"
"}\n"
"\n"
"QTableCornerButton::section {\n"
"    background-color: transparent;\n"
"    border: 1px solid rgba(0, 0, 0, 15);\n"
"}\n"
"\n"
"QTableCornerButton::section:pressed {\n"
"    background-color: rgba(0, 0, 0, 12);\n"
"}\n"
"\n"
"ListView,\n"
"ListWidget {\n"
"    background: transparent;\n"
"    background-color: rgb(255, 255, 255);\n"
"    outline: none;\n"
"    border: none;\n"
"    /* font: 13px \'Segoe UI\', \'Microsoft YaHei\'; */\n"
"    selection-background-color: transparent;\n"
"    alternate-background-color: transparent;\n"
"    padding-left: 4px;\n"
"    padding-right: 4px;\n"
"}\n"
"\n"
"ListView::item,\n"
"ListWidget::item {\n"
"    background: transparent;\n"
"    border: 1px;\n"
"    padding-left: 11px;\n"
"    padding-right: 11px;\n"
"    height: 35px;\n"
"}\n"
"\n"
"\n"
"ListView::indicator,\n"
"ListWidget::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 5px;\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    margin-right: 4px;\n"
"}\n"
"\n"
"")
        self.tbw_setting.setRowCount(50)
        self.tbw_setting.setObjectName("tbw_setting")
        self.tbw_setting.setColumnCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_setting.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_setting.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_setting.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_setting.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_setting.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_setting.setHorizontalHeaderItem(5, item)
        self.verticalLayout_4.addWidget(self.tbw_setting)
        self.horizontalLayout_6.addWidget(self.widget_setting_right)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 4)
        self.stackedWidget.addWidget(self.Item2)
        self.verticalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1038, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "转换"))
        self.Pivot.setItemText("Item1", _translate("MainWindow", "开始转换"))
        self.Pivot.setItemText("Item2", _translate("MainWindow", "转换配置"))
        self.cbb_setting.setItemText(0, _translate("MainWindow", "--选择配置文件--"))
        self.cbb_setting.setItemText(1, _translate("MainWindow", "配置1"))
        self.cbb_setting.setItemText(2, _translate("MainWindow", "配置2"))
        self.PushButton_2.setText(_translate("MainWindow", "开始转换"))
        self.PushButton_3.setText(_translate("MainWindow", "生成DDL"))
        self.PushButton.setText(_translate("MainWindow", "清空页面"))
        self.btn_add_setting.setText(_translate("MainWindow", "新增"))
        self.btn_del_setting.setText(_translate("MainWindow", "删除"))
        __sortingEnabled = self.lsw_setting.isSortingEnabled()
        self.lsw_setting.setSortingEnabled(False)
        item = self.lsw_setting.item(0)
        item.setText(_translate("MainWindow", "配置1"))
        item = self.lsw_setting.item(1)
        item.setText(_translate("MainWindow", "配置2"))
        self.lsw_setting.setSortingEnabled(__sortingEnabled)
        self.btn_save_setting.setText(_translate("MainWindow", "保存"))
        item = self.tbw_setting.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "源类型"))
        item = self.tbw_setting.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "目标类型"))
        item = self.tbw_setting.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "长度转换规则"))
        item = self.tbw_setting.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "长度转换值"))
        item = self.tbw_setting.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "精度转换规则"))
        item = self.tbw_setting.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "精度转换值"))
from qfluentwidgets import ListWidget, TableWidget
from testPageTableWidget import PageTableWidget
