# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/lojn/PycharmProjects/ljz-tools/ui/PageTableWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets

import qfluentwidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1206, 786)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tbw_table = QtWidgets.QTableWidget(Form)
        self.tbw_table.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tbw_table.setStyleSheet("\n"
"/* 如下代码设置列表左上角那个格子的边框线 */\n"
"QTableCornerButton::section{ \n"
"  border-top:0px solid #E5E5E5;\n"
"  border-left:0px solid #E5E5E5;\n"
"  border-right:0.5px solid #E5E5E5;\n"
"  border-bottom: 0.5px solid #E5E5E5;\n"
"  background-color:white;\n"
"}\n"
"/* 如下代码设置横向表格头的间隔线，有四个方向的间隔线,不需要间隔线的可以设置为0px */\n"
"QHeaderView::section{\n"
"  border-top:0px solid #E5E5E5;\n"
"  border-left:0px solid #E5E5E5;\n"
"  border-right:0.5px solid #E5E5E5;\n"
"  border-bottom: 0.5px solid #E5E5E5;\n"
"  background-color:white;\n"
"  padding:4px;\n"
"}\n"
"/* 如下代码设置纵向表格头的间隔线，有四个方向的间隔线, 不需要间隔线的可以设置为0px */\n"
"QHeaderView::section{\n"
"  border-top:0px solid #E5E5E5;\n"
"  border-left:0px solid #E5E5E5;\n"
"  border-right:0.5px solid #E5E5E5;\n"
"  border-bottom: 0.5px solid #E5E5E5;\n"
"  background-color:white;\n"
"  padding:4px;\n"
"}\n"
"/* 选中项目 */\n"
"QTableWidget::item:selected {\n"
"  background-color: rgb(225, 227, 230);  /*rgb(0, 159, 170) (225, 227, 230)*/\n"
"  border-radius: 3px; /*圆角度*/\n"
"}")
        self.tbw_table.setObjectName("tbw_table")
        self.tbw_table.setColumnCount(3)
        self.tbw_table.setRowCount(9)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_table.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_table.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_table.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_table.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_table.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbw_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_table.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_table.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_table.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_table.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_table.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_table.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_table.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_table.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_table.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_table.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_table.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_table.setItem(8, 2, item)
        self.verticalLayout.addWidget(self.tbw_table)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cbb_cnt = qfluentwidgets.ComboBox(Form)
        self.cbb_cnt.setObjectName("cbb_cnt")
        self.cbb_cnt.addItem("")
        self.cbb_cnt.addItem("")
        self.cbb_cnt.addItem("")
        self.cbb_cnt.addItem("")
        self.horizontalLayout.addWidget(self.cbb_cnt)
        self.btn_first = qfluentwidgets.PushButton(Form)
        self.btn_first.setMinimumSize(QtCore.QSize(100, 0))
        self.btn_first.setObjectName("btn_first")
        self.horizontalLayout.addWidget(self.btn_first)
        self.btn_pre = qfluentwidgets.PushButton(Form)
        self.btn_pre.setMinimumSize(QtCore.QSize(100, 0))
        self.btn_pre.setObjectName("btn_pre")
        self.horizontalLayout.addWidget(self.btn_pre)
        self.edt_cur_page = LineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edt_cur_page.sizePolicy().hasHeightForWidth())
        self.edt_cur_page.setSizePolicy(sizePolicy)
        self.edt_cur_page.setMaximumSize(QtCore.QSize(70, 16777215))
        self.edt_cur_page.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edt_cur_page.setObjectName("edt_cur_page")
        self.horizontalLayout.addWidget(self.edt_cur_page)
        self.label = StrongBodyLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lab_cnt_page = BodyLabel(Form)
        self.lab_cnt_page.setObjectName("lab_cnt_page")
        self.horizontalLayout.addWidget(self.lab_cnt_page)
        self.btn_next = qfluentwidgets.PushButton(Form)
        self.btn_next.setMinimumSize(QtCore.QSize(100, 0))
        self.btn_next.setObjectName("btn_next")
        self.horizontalLayout.addWidget(self.btn_next)
        self.btn_last = qfluentwidgets.PushButton(Form)
        self.btn_last.setMinimumSize(QtCore.QSize(100, 0))
        self.btn_last.setObjectName("btn_last")
        self.horizontalLayout.addWidget(self.btn_last)
        self.btn_jump = qfluentwidgets.PushButton(Form)
        self.btn_jump.setMinimumSize(QtCore.QSize(100, 0))
        self.btn_jump.setObjectName("btn_jump")
        self.horizontalLayout.addWidget(self.btn_jump)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_export = qfluentwidgets.PushButton(Form)
        self.btn_export.setMinimumSize(QtCore.QSize(100, 0))
        self.btn_export.setObjectName("btn_export")
        self.horizontalLayout.addWidget(self.btn_export)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "tablewidget"))
        item = self.tbw_table.verticalHeaderItem(0)
        item.setText(_translate("Form", "新建行"))
        item = self.tbw_table.verticalHeaderItem(1)
        item.setText(_translate("Form", "新建行"))
        item = self.tbw_table.verticalHeaderItem(2)
        item.setText(_translate("Form", "新建行"))
        item = self.tbw_table.verticalHeaderItem(3)
        item.setText(_translate("Form", "新建行"))
        item = self.tbw_table.verticalHeaderItem(4)
        item.setText(_translate("Form", "新建行"))
        item = self.tbw_table.verticalHeaderItem(5)
        item.setText(_translate("Form", "新建行"))
        item = self.tbw_table.verticalHeaderItem(6)
        item.setText(_translate("Form", "新建行"))
        item = self.tbw_table.verticalHeaderItem(7)
        item.setText(_translate("Form", "新建行"))
        item = self.tbw_table.verticalHeaderItem(8)
        item.setText(_translate("Form", "新建行"))
        item = self.tbw_table.horizontalHeaderItem(0)
        item.setText(_translate("Form", "新建列"))
        item = self.tbw_table.horizontalHeaderItem(1)
        item.setText(_translate("Form", "新建列"))
        item = self.tbw_table.horizontalHeaderItem(2)
        item.setText(_translate("Form", "新建列"))
        __sortingEnabled = self.tbw_table.isSortingEnabled()
        self.tbw_table.setSortingEnabled(False)
        item = self.tbw_table.item(0, 0)
        item.setText(_translate("Form", "1"))
        item = self.tbw_table.item(0, 1)
        item.setText(_translate("Form", "2"))
        item = self.tbw_table.item(0, 2)
        item.setText(_translate("Form", "a"))
        item = self.tbw_table.item(1, 0)
        item.setText(_translate("Form", "2"))
        item = self.tbw_table.item(2, 0)
        item.setText(_translate("Form", "322"))
        item = self.tbw_table.item(3, 0)
        item.setText(_translate("Form", "4"))
        item = self.tbw_table.item(4, 0)
        item.setText(_translate("Form", "5"))
        item = self.tbw_table.item(5, 0)
        item.setText(_translate("Form", "11"))
        item = self.tbw_table.item(6, 0)
        item.setText(_translate("Form", "12"))
        item = self.tbw_table.item(7, 0)
        item.setText(_translate("Form", "13"))
        item = self.tbw_table.item(8, 0)
        item.setText(_translate("Form", "123"))
        item = self.tbw_table.item(8, 1)
        item.setText(_translate("Form", "1"))
        item = self.tbw_table.item(8, 2)
        item.setText(_translate("Form", "b"))
        self.tbw_table.setSortingEnabled(__sortingEnabled)
        self.cbb_cnt.setItemText(0, _translate("Form", "100条/页"))
        self.cbb_cnt.setItemText(1, _translate("Form", "1000条/页"))
        self.cbb_cnt.setItemText(2, _translate("Form", "10000条/页"))
        self.cbb_cnt.setItemText(3, _translate("Form", "100000条/页"))
        self.btn_first.setText(_translate("Form", "首页"))
        self.btn_pre.setText(_translate("Form", "上一页"))
        self.edt_cur_page.setText(_translate("Form", "0"))
        self.label.setText(_translate("Form", "/"))
        self.lab_cnt_page.setText(_translate("Form", "0"))
        self.btn_next.setText(_translate("Form", "下一页"))
        self.btn_last.setText(_translate("Form", "尾页"))
        self.btn_jump.setText(_translate("Form", "跳转"))
        self.btn_export.setText(_translate("Form", "导出"))
from qfluentwidgets import BodyLabel, LineEdit, StrongBodyLabel
